version: "3.8"

services:

  accounts:
    image: bank/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - bank-network
    
  loans:
    image: bank/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - bank-network
    
  cards:
    image: bank/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - bank-network
    
networks:
  bank-network: